Andrew dev
Apollo-Community/ApolloStation pull request #1396
Opened 2017-02-06 18:49 UTC by Andrew-Fall

## New Pull Request

**Please follow this template to allow for better code management. PRs not following this template might be closed without notice.**

### Status (Ready for Merge, Do Not Merge, In Development)
Ready for Merge
### Changes introduced to the code/map

- Apollo
  - Bar Lighting Fix
  - Disposals Redone
  - Science Access Fix
  - Gateway and Podbay Switch
  - Hydroponic Tables in Botany Fix
  - Apollo Interior Bluespace Inducer Wired
  - SM Switched in
  - Showers for medical
- Moon
  - Large Airlock Fix
  - Toxins Test Area Drain
  - Phoron for PacMan
  - SMES changes
  - Secrets
- Other
  - Pods check surroundings before placing passengers
  - Roboticists can access Farmbots, Medibots, Floorbots, and Cleanbots.

### Comments

### PR Checklist (Organisation-sided, leave this alone)
- [ ] Code takes game balance into account.
- [ ] Code is clear and understandable.
- [ ] Code is commented.

_Maintainers: Do not merge code before the above steps are crossed out_

2017-02-06 21:20 UTC, Haldreithen requested changes
Need to comment your code a bit in code/game/vehicles/spacepods/spacepod

2017-02-07 04:43 UTC, Haldreithen approved these changes

2017-02-07 04:44 UTC, Haldreithen commented
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/apollo-community/apollostation/1396)*
<!-- Sent from Reviewable.io -->

2017-02-07 18:56 UTC, Andrew-Fall commented
Ready

2017-02-07 21:15 UTC, merged